# 04 — Institutional Research Analysis
Creates leadership-facing KPI tables for enrollment, credit completion, withdrawals, and persistence.

In [1]:
from pathlib import Path
import pandas as pd

ROOT = Path("..")
m = pd.read_csv(ROOT / "data/processed/student_term_metrics.csv")

annual = (
    m.groupby("academic_year")
    .agg(
        unique_students=("student_id","nunique"),
        attempted_credits=("credits_attempted","sum"),
        completed_credits=("credits_completed","sum"),
        withdrawals=("withdrawals","sum")
    )
)
annual["credit_completion_rate"] = annual["completed_credits"]/annual["attempted_credits"]
annual

               unique_students  ...  credit_completion_rate
academic_year                   ...
2022                      1518  ...                0.889792
2023                      6357  ...                0.892507
2024                     10074  ...                0.891776
2025                     16493  ...                0.892445
2026                      8481  ...                0.888154

[5 rows x 5 columns]

In [2]:
persistence = (
    m[m["eligible_for_next_term"].eq(1)]
    .groupby(["academic_year","program"])["enrolled_next_term"]
    .mean()
    .reset_index(name="next_term_persistence_rate")
)
persistence.sort_values(["academic_year","next_term_persistence_rate"]).head(12)

    academic_year                    program  next_term_persistence_rate
5            2022                 Psychology                    0.695971
2            2022          Education Studies                    0.696517
4            2022     Information Technology                    0.707581
1            2022              Communication                    0.732484
0            2022    Business Administration                    0.740360
3            2022  Healthcare Administration                    0.773756
9            2023  Healthcare Administration                    0.715351
11           2023                 Psychology                    0.723773
7            2023              Communication                    0.728829
6            2023    Business Administration                    0.730979
10           2023     Information Technology                    0.735471
8            2023          Education Studies                    0.738451

Use **observed**, **associated**, and **descriptive** wording; this workflow does not establish causal effects.